create table public.events (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid references auth.users not null,
  event_name text not null,
  event_type text not null,
  event_date date not null,
  start_time time not null,
  end_time time not null,
  venue_name text not null,
  full_address text,
  expected_attendance integer,
  latitude double precision,
  longitude double precision,
  geofence_radius integer default 100,
  services jsonb default '{"rfid":false,"geofencing":false,"facialRecognition":false}'::jsonb,
  geofence_checkin_window integer default 0,
  geofence_early_checkout_allowed integer default 0,
  geofence_late_checkout_allowed integer default 0,
  geofence_checkout_window integer default 0,
  geofence_early_checkin_allowed integer default 0,
  geofence_late_checkin_allowed integer default 0,
  geofence_late_checkin_threshold_minutes integer default 15,
  geofence_reverify_minutes integer default 15,
  notes text,
  estimated_scope integer,
  status text default 'pending_approval',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);